name: kickly
description: "kickly"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
    - assets/splash/

  fonts:
    - family: Mulish
      fonts:
        - asset: font/Mulish-Bold.ttf
        - asset: font/Mulish-Regular.ttf
        - asset: font/Mulish-SemiBold.ttf
        - asset: font/Mulish-ExtraBold.ttf
